# Generated by Django 4.2.2 on 2023-07-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="building",
            name="building_name",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_address",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_firstname",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invigilator",
            name="Invigilator_lastname",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="building_name",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="home.building",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="room_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
