# Generated by Django 4.2.3 on 2023-07-08 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examhallsession",
            old_name="invigilator",
            new_name="invigilators",
        ),
    ]
