# Generated by Django 4.2.3 on 2023-07-08 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_invigilator_examhallsession_invigilators"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Faculties"},
        ),
    ]
