# Generated by Django 4.2.3 on 2023-07-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_faculty_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examhallsession",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="home.room",
            ),
            preserve_default=False,
        ),
    ]
