# Generated by Django 4.2.3 on 2023-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="regular_or_back",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("Back", "Back")],
                default="Regular",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="semester_type",
            field=models.CharField(
                choices=[("Odd", "odd"), ("Even", "Even")], default="Odd", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="shift",
            field=models.CharField(
                choices=[("Morning", "Morning"), ("Day", "Day")],
                default="Day",
                max_length=255,
            ),
        ),
    ]
