# Generated by Django 4.2.3 on 2023-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_examhallsession_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examhallsession",
            name="shift",
            field=models.CharField(
                choices=[("Morning", "Morning"), ("Day", "Day")], max_length=255
            ),
        ),
    ]
