# Generated by Django 4.2.3 on 2023-07-11 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_building_slug_exam_slug_examhallsession_slug_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invigilator",
            unique_together={("firstname", "lastname", "email")},
        ),
    ]
