# Generated by Django 4.2.3 on 2023-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_invigilator_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invigilator",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
