# Generated by Django 4.2.3 on 2023-07-30 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_invigilator_post_alter_invigilator_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invigilator",
            name="age",
        ),
    ]
