# Generated by Django 4.2.3 on 2023-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_invigilator_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="invigilator",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
