# Generated by Django 4.2.3 on 2023-07-30 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_invigilator_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examhallsession",
            options={"ordering": ["room__building"]},
        ),
    ]
