# Generated by Django 4.2.3 on 2023-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_shift_alter_exam_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="shift",
        ),
        migrations.AddField(
            model_name="exam",
            name="shift",
            field=models.ManyToManyField(to="home.shift"),
        ),
    ]
