# Generated by Django 4.2.3 on 2023-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_invigilator_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invigilator",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE"), ("OTHERS", "OTHERS")],
                default="MALE",
                max_length=7,
            ),
        ),
    ]
